# Generated by Django 5.1.7 on 2025-09-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_annonce_annonceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='dedouaner',
            field=models.BooleanField(default=False),
        ),
    ]
